services:
  postgres:
    image: docker.io/library/postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=250'
    restart: always
    image: docker.mirrors.ustc.edu.cn/library/postgres:latest

